# Generated by Django 2.1.5 on 2019-03-10 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movichome', '0005_pagescrape_description_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBPScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('DBPDefinition', models.CharField(max_length=10000)),
                ('peribahasa', models.CharField(max_length=2000)),
                ('pantun', models.CharField(max_length=2000)),
                ('pub_date_dbp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MCPScrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('MCPList', models.CharField(max_length=10000)),
                ('description_2', models.CharField(max_length=10000)),
                ('pub_date_mcp', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pagescrape',
            name='description',
        ),
        migrations.RemoveField(
            model_name='pagescrape',
            name='description_2',
        ),
    ]
