# Generated by Django 2.1.5 on 2019-03-09 20:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movichome', '0005_pagescrape_description_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagescrape',
            old_name='description',
            new_name='DBPDefinition',
        ),
        migrations.AddField(
            model_name='pagescrape',
            name='MCPList',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagescrape',
            name='pantun',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagescrape',
            name='peribahasa',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
